version: '1'

services:
  app:
    build: .
    container_name: lyikservices
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true  # Define Docker environment
    volumes:
      - uploads:/data/uploads

  nginx:
    image: nginx:latest
    container_name: lyik_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: lyik_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot --email you@example.com --agree-tos --no-eff-email --force-renewal -d lyikservices.lyik.com -d www.lyikservices.lyik.com"

volumes:
  uploads:  # Persistent volume for file uploads
